### ISSUE TITLE
Feature request - Add `immediately` option 

### ISSUE THREAD

**Issue by KentonParton** [AbianS/zustand-debounce#4]
I created a discussion on zustand which I think would be a great feature for `zustand-debounce`, specifically, the ability to optionally update AsyncStorage immediately.

https://github.com/pmndrs/zustand/discussions/2400

**Comment by KentonParton** [comment]
@AbianS is this something you'd be open to adding? Thanks!

**Comment by AbianS** [comment]
Hi @KentonParton, if I’m not mistaken, you’re suggesting that I add an `immediately` option, which would be a boolean. If set to true, it will immediately update the state without considering the debounce time. Is that correct?

**Comment by KentonParton** [comment]
Hi @AbianS, yes, that's correct.
